baseURL = ''
languageCode = 'en-us'
title = 'Praxis Manual'
themesDir="themes"
theme="relearn"

[outputs]
home = [ "HTML", "RSS", "SEARCH", "PRINT" ]
section = ["HTML", "RSS", "PRINT"]
page = ["HTML", "RSS", "PRINT"]

[params]
alwaysOpen = false
collapsibleMenu = true
themeVariant = ["blue","green","relearn-dark"]