baseURL = 'https://endearing-halva-664fec.netlify.app/'
languageCode = 'en-us'
title = 'Praxis Manual'
themesDir = 'themes'
theme = 'leren'
 
[outputs]
home = [ "HTML", "RSS", "SEARCH", "PRINT" ]
section = ["HTML", "RSS", "PRINT"]
page = ["HTML", "RSS", "PRINT"]

[params]
alwaysOpen = false
collapsibleMenu = true
themeVariant = ["blue","green","red","relearn-dark"]

[markup.goldmark.renderer] 
unsafe= true